### ISSUE TITLE
Allow localized `-edited` suffix

### ISSUE THREAD

**Issue by 6temes** [inakaboy/google-photos-exif#5]
If the user has their Google Photos localized in a language that is not English, the suffix of the edited pictures will be translated.

Add the option to configure the suffixes for different languages.

**Comment by 6temes** [comment]
By the way, I opened the issue (and I will open a PR to your fork) because I realized that you are the only one working recently on this project.

I wanted to contact you, but I could not find your email. Feel free to contact me if you want to coordinate with me. My email is on my profile.

**Comment by inakaboy** [comment]
Hi @6temes sorry I missed notifications on this for quite some time. I've merged your requests and thanks for your contribution! Looks like whomever needs localized suffixes still needs to add them manually to the suffix array, but that's fine, this at least gives the framework for doing so. Marking the issue as fixed for now.
